name: 'myfirstwebapp'
version: '2'
services:
  app:
    container_name: 'app'
    build: .
    command: 'uvicorn main:app --reload --host 0.0.0.0 --port 8000'
    ports:
      # host ip : host port : container port
      - 0.0.0.0:8080:8000
  nginx:
    container_name: 'nginx'
    image: nginx
    ports:
      # host port : container port
      - 3080:80
